{% set version = '1.0.4' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-oceanview
  version: {{ version|replace("-", "_") }}

source:
  fn: OceanView_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/OceanView_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/OceanView/OceanView_{{ version }}.tar.gz
  sha256: e67f6f376737e1e5cf22fdfe2769a8f674e90c886b0e43942e97d9a3e6924f1c

build:
  merge_build_host: True  # [win]
  number: 2
  # no osx package for r-plot3drgl
  skip: true  # [win32 or osx]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-plot3d
    - r-plot3drgl
    - r-rgl
    - r-shape

  run:
    - r-base
    - r-plot3d
    - r-plot3drgl
    - r-rgl
    - r-shape

test:
  commands:
    - $R -e "library('OceanView')"  # [not win]
    - "\"%R%\" -e \"library('OceanView')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=OceanView
  license: GPL (>= 3.0)
  summary: Functions for transforming and viewing 2-D and 3-D (oceanographic) data and model
    output.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - conda-forge/r
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
