travis:
  secure:
    BINSTAR_TOKEN: otESweOyqcira4PfEvJxXtFooHyJR2Fu029oFN9d/3/Cev6PvLxihEuLwZxeT3nEvjdf1/+bYnQ529aZ4xHUDRITVpc5b8jdWH5z69lcqeoz1bu/60ZWksneeaIJlDcIcwc1RCqONUREE9LO4NllQI2X4zDGLXt1nBmOONLdfk/mc+w1Z5ThEjDyWxmp1gM6VTZ6Y92IM9EfQwGOZRt+02UQinpz4I5CWwhavRr2CRjlMmUYwxrL6bJOSdtKkUC2z/taQworr7nDfWaeruU8VMnLL6Z5Wm6yWif1PwYUOO4CARGqt3TASz1BJhQDaY9OX+5bqqqznS309Fop4aGR7MH4mrMmLOGt3hxJXQY9Ie0r5MguDGz0hwgeAXaxqcby9qXEIvxixNcdY6RILiAXiTMcumc/+W4GASAAWdmmC8Sqd37RrEO1U3HmR898FXDdey2Y4gdu/XjyP72FnwLF76ypwL7DP1srO9kO44O5BsS4E5sDSzyjY2VHi0m9pfP71Ba6+Ge6BL1xq2Sbue+RBfB0sZpyTYHWAluh+iDYdtKc5jqt9gQlD8ZFNN1o2Kwh9YXCOkwrFvkVATSQzt2Kyr9euE+EzVtpb3QGpvAc+ePJF4FSbUeMRVHBloteSLmcbMJYoncpya8smoXx3rx1G5Tl7LZiSoIfallcW35wSdQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
