appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: h21QrgbQ2KMbotGZD7beTj564j3BwtzCfRl7ANGWRLGOtZYqoJbmGx3oEkV+nmNw465IT61YNu2UJO0QU07jTfCu0S7QlTnQZVa5azC8Ml9FmLfEA9jqyEPmNzpkf4qtvMpOy16gfWuGFT3wbArmEs0UOqIRKZrQ6Td96KhPqMdG6/BKklHf+MXDcaJnJgEGBfGku+/42IQkhQIseF88bcui+htkfu5+Hd9MpVB1Eo0Lw9ixEti0MjcuVpFx9/lWHaTjPdrVVk9CMfcFg/gF961jKqbofNsv0IQIZK3fU3hNh9dhnMsgL+nsjWu447KVste/2TM2lKjq3jJxKfy52hUPpn1o9LRyKf9MwRk6M7MRFZE7fn5NwOcBSzxSQBk+GH9E0tmuEOIWGNqW7xL6fSoApieA1qg+mXA5W/AiTUeqJ6OAgFc7gzA+TAI5RND0U5anBGJabpduNYbpR7mnAffDKkYhQQsgOOSvZu25rCufqfP+MNOg+L6aKoO3uWinWKG4s/Jbv41KA/H7p52EC3nu3E9oqdrY/8xTQigozgobcbSEGweHRfP/mFoFC/zYEMsTA2jocHuvwUK9R0hWnDUriNCWZxx3YQfrvoDebzSScGM8VVwukr2HtB8j1hU7R/A0VFSjp7uFUH6nYgWDCwKAC72p+JlY+IwSKOUvLDQ=}
bot:
  automerge: true
